---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: must-pass
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request, push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "2"
spec:
  pipelineSpec:
    tasks:
      - name: must-pass-task
        taskSpec:
          steps:
            - name: pass-step
              image: alpine:latest
              script: |
                #!/bin/sh
                echo "✅ must-pass"
                sleep 2
                exit 0

