---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: must-fail
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request, push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "2"
spec:
  pipelineSpec:
    tasks:
      - name: must-fail-task
        taskSpec:
          steps:
            - name: fail-step
              image: alpine:latest
              script: |
                #!/bin/sh
                echo "❌ must-fail"
                sleep 2
                exit 1

